[package]
name = "hinode"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astrolabe = "0.5.1"
clap = { version = "4.5.1", features = ["derive"] }
shellwords = "1.1.0"
sunrise = "1.0.1"
